/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as LevantamentosIndexRouteImport } from './routes/levantamentos.index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as LevantamentosNovoRouteImport } from './routes/levantamentos.novo'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as LevantamentosIdIndexRouteImport } from './routes/levantamentos.$id.index'
import { Route as LevantamentosIdResumoRouteImport } from './routes/levantamentos.$id.resumo'
import { Route as ConfiguracoesTiposTypeIdRouteImport } from './routes/configuracoes.tipos.$typeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIndexRoute = LevantamentosIndexRouteImport.update({
  id: '/levantamentos/',
  path: '/levantamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosNovoRoute = LevantamentosNovoRouteImport.update({
  id: '/levantamentos/novo',
  path: '/levantamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIdIndexRoute = LevantamentosIdIndexRouteImport.update({
  id: '/levantamentos/$id/',
  path: '/levantamentos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIdResumoRoute = LevantamentosIdResumoRouteImport.update({
  id: '/levantamentos/$id/resumo',
  path: '/levantamentos/$id/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesTiposTypeIdRoute =
  ConfiguracoesTiposTypeIdRouteImport.update({
    id: '/tipos/$typeId',
    path: '/tipos/$typeId',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/levantamentos/': typeof LevantamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id/': typeof LevantamentosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/levantamentos': typeof LevantamentosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id': typeof LevantamentosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/levantamentos/': typeof LevantamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id/': typeof LevantamentosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/projetos/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/levantamentos/'
    | '/projetos/'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/projetos/$id'
    | '/clientes'
    | '/configuracoes'
    | '/levantamentos'
    | '/projetos'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/login'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/projetos/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/levantamentos/'
    | '/projetos/'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClientesIdRoute: typeof ClientesIdRoute
  LevantamentosNovoRoute: typeof LevantamentosNovoRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  LevantamentosIndexRoute: typeof LevantamentosIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  LevantamentosIdResumoRoute: typeof LevantamentosIdResumoRoute
  LevantamentosIdIndexRoute: typeof LevantamentosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/': {
      id: '/levantamentos/'
      path: '/levantamentos'
      fullPath: '/levantamentos/'
      preLoaderRoute: typeof LevantamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/novo': {
      id: '/levantamentos/novo'
      path: '/levantamentos/novo'
      fullPath: '/levantamentos/novo'
      preLoaderRoute: typeof LevantamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/$id/': {
      id: '/levantamentos/$id/'
      path: '/levantamentos/$id'
      fullPath: '/levantamentos/$id/'
      preLoaderRoute: typeof LevantamentosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/$id/resumo': {
      id: '/levantamentos/$id/resumo'
      path: '/levantamentos/$id/resumo'
      fullPath: '/levantamentos/$id/resumo'
      preLoaderRoute: typeof LevantamentosIdResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/tipos/$typeId': {
      id: '/configuracoes/tipos/$typeId'
      path: '/tipos/$typeId'
      fullPath: '/configuracoes/tipos/$typeId'
      preLoaderRoute: typeof ConfiguracoesTiposTypeIdRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  ConfiguracoesTiposTypeIdRoute: typeof ConfiguracoesTiposTypeIdRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  ConfiguracoesTiposTypeIdRoute: ConfiguracoesTiposTypeIdRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  LoginRoute: LoginRoute,
  ClientesIdRoute: ClientesIdRoute,
  LevantamentosNovoRoute: LevantamentosNovoRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  LevantamentosIndexRoute: LevantamentosIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  LevantamentosIdResumoRoute: LevantamentosIdResumoRoute,
  LevantamentosIdIndexRoute: LevantamentosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
